export const loginConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED"
}
export const quizDataConstants ={
    QUIZDATA_REQUEST: "QUIZDATA_REQUEST",
    QUIZDATA_SUCCESS: "QUIZDATA_SUCCESS",
    QUIZDATA_FAILED:  "QUIZDATA_FAILED",
    UPDATE_QUIZ_SCORE: "UPDATE_QUIZ_SCORE"
}